//
// httpget.cpp
//
// $Id: //poco/1.4/Net/samples/httpget/src/httpget.cpp#1 $
//
// This sample demonstrates the HTTPClientSession class.
//
// Copyright (c) 2005-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#include "Poco/Net/HTTPClientSession.h"
#include "Poco/Net/HTTPRequest.h"
#include "Poco/Net/HTTPResponse.h"
#include "Poco/Net/MediaType.h"
#include "Poco/StreamCopier.h"
#include "Poco/Path.h"
#include "Poco/URI.h"
#include "Poco/Exception.h"
#include <iostream>
#include <sstream>
#include "PointerCollection.h"
#include "Filehash.h"

using Poco::Net::HTTPClientSession;
using Poco::Net::HTTPRequest;
using Poco::Net::HTTPResponse;
using Poco::Net::HTTPMessage;
using Poco::Net::MediaType;
using Poco::StreamCopier;
using Poco::Path;
using Poco::URI;
using Poco::Exception;


std::string get(std::string url){
    std::string out;
    try
    {
        URI uri(url);
        //URI uri("http://localhost:8080");
        std::string path(uri.getPathAndQuery());
        if (path.empty()) path = "/";

        HTTPClientSession session(uri.getHost(), uri.getPort());
        HTTPRequest req(HTTPRequest::HTTP_GET, path, HTTPMessage::HTTP_1_1);
        req.add("Accept","text/xml");
        session.sendRequest(req);
        HTTPResponse res;
        std::istream& rs = session.receiveResponse(res);
        std::cout << res.getStatus() << " " << res.getReason() << std::endl;

        StreamCopier::copyToString(rs,out);
    }
    catch (Exception& exc)
    {
        std::cerr << exc.displayText() << std::endl;
        return "-1";
    }

    return out;
}

int main(int argc, char** argv)
{
    std::string pointer;

    pointer = get("http://voldemort.cs.cf.ac.uk:7048/dl/meta/pointer/");

    if(pointer == "-1"){
        return 1;
    }

    PointerCollection* p = new PointerCollection(pointer.c_str());

    list<DataPointer>::iterator i;

    for(i = p->dp->begin(); i != p->dp->end(); i++){
        list<Endpoint>::iterator e;

        for(e = (*i).ep->begin(); e != (*i).ep->end(); e++){
            std::stringstream ss;
            ss << (*e).meta << "?filehash=" << (*i).dd->id;
            std::string out = get(ss.str());
            
            if(out != "-1"){
                Filehash* f = new Filehash(out.c_str());
                std::cout << f->toString();
            }
            std::cout << "\n";
        }
    }

    std::cout << p->toString();
    return 0;
}

